services:
  - type: web
    name: ct-zone
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: echo "Building using Dockerfile..."
    startCommand: apache2-foreground
    envVars:
      - key: APP_NAME
        value: "CT ZONE"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: ct-zone
          property: host
      - key: DB_CONNECTION
        value: mysql
    disk:
      name: ct-zone-storage
      mountPath: /var/www/html/storage
      sizeGB: 10
    healthCheckPath: /
    numInstances: 1

# Define persistent disk to store Laravel storage data
disks:
  - name: ct-zone-storage
    mountPath: /var/www/html/storage
    sizeGB: 10 